library identifier: 'jenkins-pipeline-demo-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/sixeyed/jenkins-pipeline-demo-library.git'])

crossPlatformBuild repoName: 'maqueda/pi-psod-pipelines',
                   linuxContext: 'm4', 
                   windowsContext: 'm4'
